### ISSUE TITLE
Warning when loading orcidlink before float package

### ISSUE THREAD

**Issue by stertooy** [duetosymmetry/orcidlink-LaTeX-command#10]
If the orcidlink package is loaded before the float package, and a float environment with caption is present, warnings about duplicate identifiers pop up. MWE:

```
\documentclass{article}

\usepackage{orcidlink}
\usepackage{float}

\begin{document}
    \begin{table}
        \caption{Caption}
    \end{table}
\end{document}
```
produces the warning
```
pdfTeX warning (ext4): destination with the same identifier (name{table.1}) has
 been already used, duplicate ignored
```
However, when I put orcidlink after float, then compiling
```
\documentclass{article}

\usepackage{float}
\usepackage{orcidlink}

\begin{document}
    \begin{table}
        \caption{Caption}
    \end{table}
\end{document}
```
does not produce any warnings.

These warnings seem harmless, nothing seems off in the pdf output and the "fix" is quite simple, but I figured I'd report it anyway...

**Comment by duetosymmetry** [comment]
Interesting! Does this happen with just (float,hyperref) or just (float,tikz) instead of (float,orcidlink)?

**Comment by stertooy** [comment]
Ah... Yes, it does happen with just float and hyperref - and looking at [this TeX.StackExchange comment](https://tex.stackexchange.com/questions/134847/hyperref-and-the-float-package#comment1275704_134847), that's nothing new. My bad!

**Comment by duetosymmetry** [comment]
Great, thanks for tracking down the underlying issue!
