### ISSUE TITLE
Proposal: \orcidlinki without name being hyperlinked

### ISSUE THREAD

**Issue by nielsbock** [duetosymmetry/orcidlink-LaTeX-command#13]
Would it be possible to have an inline orcid logo without having to hyperlink the name also?  Maybe both options could be available so you could choose between `\orcidlinkin{Name}{orcid}` and `\orcidlinki{orcid}`. I can see in the ORCID Brand Guidelines that linking the previous text is only optional for inline, so this would still be in line with the guidelines (https://info.orcid.org/brand-guidelines/).

**Comment by duetosymmetry** [comment]
I think an easier solution would just be:
```
Niels Bock \orcidlink{0009-0005-7373-1589}
```
which will result in the name not being hyperlinked, but the ORCiD logo being hyperlinked.

**Comment by nielsbock** [comment]
Oh, my bad. I had recently used `\orcidlink` successfully but yesterday I had some issues. I thought that this was due to the new update, but the issue was unrelated to this.
