### ISSUE TITLE
Desactivating gloabal style for orcidlink command

### ISSUE THREAD

**Issue by aubertc** [duetosymmetry/orcidlink-LaTeX-command#4]
This may be outside the scope of this package, but is there a way to make `orcidlink` "robust" to changes in tizk style?

The following:

```tex
\documentclass{article}
\usepackage{orcidlink}
\tikzset{%
	every picture/.append style={anchor=base, baseline} % I want every picture to be placed on baseline
}
\begin{document}
	My name\orcidlink{0000-0001-6346-3043}
\end{document}
```

produces the ugly placement:

![Screenshot_20221209_130925](https://user-images.githubusercontent.com/16466689/206765758-f632876a-4335-4e18-8504-8e626e467cba.png)

Now, I know that "I got what I have asked for" with my `tikzset` command, but was wondering if there was a way in the package to override this choice.

**Comment by aubertc** [comment]
Thanks! My question was whenever the _package_ could add this feature.
I imagine that around https://github.com/duetosymmetry/orcidlink-LaTeX-command/blob/50348339950e6aca379b6d0e9b08944ea974171f/orcidlink.sty#L56 one could add `anchor=top` and something to reset the baseline to its default value (which should be `0pt` according to the manual, but that did not seem to cancel my edits in tikzstyle, so, not sure…).

**Comment by duetosymmetry** [comment]
I think it's inappropriate for the package to override the choice that the user makes about the baseline — what if the user really does want to change the baseline? I think a more user-friendly solution would be to name the orcidlink picture's style so that the user can modify it if they want to.

**Comment by aubertc** [comment]
Ok, I see your point. Thanks a lot.

**Comment by duetosymmetry** [comment]
We can edit this issue to instead be something like "Name the orcidlink tikzpicture's style and expose it so the user can modify it". Is that something you think others would find useful?

**Comment by aubertc** [comment]
Honestly, no.

But thanks a lot for offering, I appreciate it.
