### ISSUE TITLE
Swagger is not available until further notice due to a maintenance upgrade

### ISSUE THREAD

**Issue by luigisopa** [duetosymmetry/orcidlink-LaTeX-command#6]
https://pub.orcid.org/v3.0/ is not reachable with current API. 

R error after orcid_search():

Error: Unauthorized (HTTP 401).
401 Unauthorized: The client application is not authorized for this ORCID record. Full validation error: Access token is for a different record

**Comment by duetosymmetry** [comment]
This is not a LaTeX issue with the package, but rather a web issue with contacting the ORCiD server.
